/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary-container': "#d8e2ff",
        'secondary-dim': "#525357",
        'on-primary-fixed': "#003d85",
        'tertiary-fixed': "#d8d3f4",
        'on-secondary-fixed-variant': "#5b5b60",
        'secondary-fixed': "#e3e2e7",
        'primary-dim': "#004faa",
        'surface-bright': "#f9f9fe",
        'secondary-fixed-dim': "#d5d4d9",
        'background': "#f9f9fe",
        'surface-tint': "#005bc1",
        'outline-variant': "#acb2bf",
        'on-tertiary': "#fcf7ff",
        'on-surface': "#2c333d",
        'on-background': "#2c333d",
        'on-secondary-fixed': "#3e3f43",
        'error-dim': "#4e0309",
        'outline': "#747b86",
        'surface-container-high': "#e4e8f3",
        'error-container': "#fe8983",
        'surface-container-lowest': "#ffffff",
        'tertiary-container': "#d8d3f4",
        'primary-fixed': "#d8e2ff",
        'on-tertiary-container': "#4a4863",
        'on-primary-container': "#004ea8",
        'surface-variant': "#dce3f0",
        'on-error': "#fff7f6",
        'on-secondary-container': "#515156",
        'on-primary': "#f7f7ff",
        'on-error-container': "#752121",
        'secondary': "#5e5f63",
        'surface-container': "#ebeef7",
        'error': "#9f403d",
        'primary': "#005bc1",
        'inverse-on-surface': "#9c9da1",
        'on-surface-variant': "#595f6a",
        'tertiary-dim': "#53506b",
        'inverse-surface': "#0c0e12",
        'surface-container-highest': "#dce3f0",
        'surface-container-low': "#f2f3fa",
        'tertiary-fixed-dim': "#cac6e6",
        'on-secondary': "#f9f8fe",
        'surface-dim': "#d3dae9",
        'surface': "#f9f9fe",
        'primary-fixed-dim': "#c2d4ff",
        'on-tertiary-fixed-variant': "#54516d",
        'tertiary': "#5f5c78",
        'on-tertiary-fixed': "#37354f",
        'secondary-container': "#e3e2e7",
        'on-primary-fixed-variant': "#0058bb",
        'inverse-primary': "#4b8eff"
      },
      fontFamily: {
        'headline': ["Inter"],
        'body': ["Inter"],
        'label': ["Inter"]
      },
    },
  },
  plugins: [],
}
